FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    htop \
    vim \
    tmux \
    fzf \
    tree \
    curl \
    wget \
    git \
    jq \
    zsh \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    nibabel \
    nilearn \
    pandas \
    matplotlib \
    jupyterlab

WORKDIR /bids
CMD ["zsh"]
