services:

  freesurfer:
    image: freesurfer/freesurfer:8.2.0
    volumes:
      - ${FS_LICENSE}:/usr/local/freesurfer/8.2.0-1/license.txt:ro
      - ${BIDS_DIR}:/bids:ro
      - ${RESEARCH_DIR}:/research
    environment:
      - SUBJECTS_DIR=/research/advancedVolumetry/freesurfer_derived_subject_data/
    stdin_open: true
    tty: true
    profiles: ["freesurfer"]

  mrtrix:
    image: mrtrix3/mrtrix3:latest
    volumes:
      - ${BIDS_DIR}:/bids:ro
      - ${RESEARCH_DIR}:/research
    stdin_open: true
    tty: true
    profiles: ["mrtrix"]

  ants:
    image: antsx/ants:latest
    volumes:
      - ${BIDS_DIR}:/bids:ro
      - ${RESEARCH_DIR}:/research
    stdin_open: true
    tty: true
    profiles: ["ants"]
